global:
  scrape_interval: 15s # How often Prometheus will scrape metrics.

scrape_configs:
  - job_name: 'monitoringdemo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8085']